[theme]
base="light"
primaryColor="#3A81C7"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f5f5f5"
textColor="#000000"
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
